name: higher-rank
version: '0.0.0'
category: Other
synopsis: A new Haskell package.
description: higher-rank is a new Haskell package.
maintainer: Ningning Xie

extra-source-files:
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall
default-extensions:
- ApplicativeDo
- GeneralizedNewtypeDeriving
- LambdaCase
- StandaloneDeriving

library:
  dependencies:
  - base
  - containers
  - haskeline
  - megaparsec
  - mtl
  - scientific
  - unbound-generics
  - prettyprinter
  source-dirs: library

executables:
  higher-rank:
    dependencies:
    - base
    - higher-rank
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
